[package]
name = "aoc_2024"
authors = ["Rareș Cosma <rares@getbetter.ro>"]
version = "0.1.0"
edition = "2021"
default-run = "aoc_2024"

[dependencies]
aoc_2dmap.workspace = true
aoc_prelude.workspace = true
aoc_dijsktra.workspace = true

rayon.workspace = true
regex.workspace = true
